# .NET Build Configuration
version: '{build}'
image: Visual Studio 2019

init:
- net start MSSQL$SQL2019

before_build:
- ps: .nuget\BuildInit.ps1
- cmd: nuget restore

build:
  verbosity: minimal
configuration: Release
skip_tags: true

# .NET Tests
test:
  assemblies:
    only:
    - '**\kentico.*.Tests.dll'
# Test against the latest version of this Node.js version
environment:
  nodejs_version: "10"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  - npm run build

after_build:
  - ps: .nuget\CreatePackages.ps1

# Post-install test scripts.
after_test:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run test

test_script:
- nunit3-console.exe "C:\projects\ems-mvc-components\Kentico.Selector.ObjectSelector.Tests\bin\Release\Kentico.Selector.ObjectSelector.Tests.dll" --result=myresults.xml;format=AppVeyor --workers=1

artifacts:
  - path: '*.nupkg'
    name: NuGet packages
  - path: TestDatabases.zip
    name: TestDatabases

on_failure:
 - ps: 7z a TestDatabases.zip TestDatabases\*
 - ps: Push-AppveyorArtifact TestDatabases.zip
